### ISSUE TITLE
Please support sinon v2.0.0

### ISSUE THREAD

**Issue by nikwen** [elliotf/mocha-sinon#12]
sinon v2.0.0 has been [released](https://github.com/sinonjs/sinon/releases/tag/v2.0.0) but is not yet compatible with mocha-sinon.

It would be great if someone could update this package. :)

**Comment by elliotf** [comment]
I hope that you think this result is great.  You shouldn't have any more problems with dependency versions anymore.

**Comment by nikwen** [comment]
@elliotf Thanks for fixing this. :)

**Comment by elliotf** [comment]
np!
