### ISSUE TITLE
"mocha-sinon relies on mocha having been loaded." with mocha 3.4.2

### ISSUE THREAD

**Issue by titarenko** [elliotf/mocha-sinon#15]
Hi!

Thanks for the lib! Unfortunately cant get it work with mocha 3.4.2

```
node_modules/mocha-sinon/mocha-sinon.js:5
    throw "mocha-sinon relies on mocha having been loaded.";
    ^
mocha-sinon relies on mocha having been loaded.
```

It seems like mocha does not expose `beforeEach` for modules required using cli args:

`mocha -r mocha-sinon -r should -r should-sinon --recursive tests`

Is there some solution for this?

**Comment by anfho93** [comment]
Any Idea of how to solve this?

**Comment by jbiggi** [comment]
Has anyone figured out how to fix this issue yet?

**Comment by haximilian** [comment]
Have you tried writing `require("mocha-sinon");` at the top of your test file? Or maybe just updating to a more recent version of mocha?
Perhaps a little more detail on the nature of your situation would be helpful in providing a proper solution.

**Comment by Lakitna** [comment]
I'm also running into this issue in Mocha 5.2.0, Mocha-sinon 2.1.0 and Sinon 7.1.1.

This only happens when you try to require Mocha-sinon via the command line (or mocha.opts).

**Comment by elliotf** [comment]
Hello, all. I don't use this module anymore, and instead use the following boilerplate in each of my projects' test helper:

```javascript
beforeEach(function() {
  if (this.sinon) {
    this.sinon.restore()
  } else {
    this.sinon = sinon.createSandbox()
  }
})
```

That said, it looks like either
a) I was wrong when I wrote the documentation for this module, or
b) mocha changed how it behaves when it comes to initializing its global `beforeEach` method.

I'm not sure which one it is, and I'm not going to explore it, so I welcome suggestions of what should be done. I think the easiest thing for me to do is to correct the documentation, removing the part that says that you can require it on the command line.

I welcome suggestions!
