### ISSUE TITLE
Make "sinon" an actual dependency

### ISSUE THREAD

**Issue by buck-ross** [elliotf/mocha-sinon#18]
Is there any particular reason that `sinon` remains as a dev-dependency as opposed to just a plain dependency? It just seems kind of redundant to have to type `npm i -D sinon mocha-sinon` instead of just installing `mocha-sinon` and letting it install `sinon` automatically.

**Comment by haximilian** [comment]
Come to think of it, `mocha` should probably be added as a proper dependency too.

**Comment by HoldYourWaffle** [comment]
I agree that `sinon` should be added as a regular dependency, and `mocha` could(/should) probably be added as a peer dependency.
