### ISSUE TITLE
Question: why do we need create new sandbox before each test?

### ISSUE THREAD

**Issue by Alexsey** [elliotf/mocha-sinon#8]
You recommend to use code like
```
var sinon = require('sinon');

beforeEach(function() {
  this.sinon = sinon.sandbox.create();
});

afterEach(function(){
  this.sinon.restore();
});
```
and something similar is happening inside module itself. What are the pros of such solution comparing to
```
var sinon = require('sinon').sandbox.create();

afterEach(function(){
  sinon.restore();
});
```
?

**Comment by elliotf** [comment]
Probably not much at all.  It might be an interesting thing to benchmark.  Please let me know if you find a difference.  :)

In the latter one that you list will need/want to export/expose the sinon sandbox instance you created, though.  Similar to what you wrote, for some projects, I do:

```javascript
beforeEach(function() {
  if (this.sinon) {
    this.sinon.restore();
  } else {
    this.sinon = sinon.sandbox.create();
  }
});
```

If I'm working on someone else's project and don't want to add a dependency. Really, they should all work just fine.  The main takeaway is to have a sinon sandbox that auto-cleans up after itself.

**Comment by Alexsey** [comment]
Thanks for quick answer :+1:  if I'll find any - I will write it here :)
